#!/bin/sh
# Copyright 2020 Collabora Ltd.
# SPDX-License-Identifier: MIT

set -eux

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cd "$AUTOPKGTEST_TMP"

cat > trivial.c <<EOF
#include <babl/babl.h>

#undef NDEBUG
#include <assert.h>

int main(void)
{
    int x, y, z;

    babl_get_version(&x, &y, &z);
    assert(x >= 0);
    assert(y >= 0);
    assert(z >= 0);
    assert((x * 1000) + y >= 1);
    return 0;
}
EOF

# Deliberately word-splitting pkg-config's output:
# shellcheck disable=SC2046
"${CROSS_COMPILE}gcc" -otrivial trivial.c $("${CROSS_COMPILE}pkg-config" --cflags --libs babl)
./trivial
